// <auto-generated />
namespace TakeyourStand.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TYS75 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TYS75));
        
        string IMigrationMetadata.Id
        {
            get { return "202303121831159_TYS7.5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
