// <auto-generated />
namespace TakeyourStand.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TYS76 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TYS76));
        
        string IMigrationMetadata.Id
        {
            get { return "202303121959210_TYS7.6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
